[package]
name = "rust_call_ifttt_webhook_api"
version = "0.1.0"
authors = ["mkXultra <eeapprenctice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
